# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json
from pprint import pprint

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
#load the dataframe
city_df = pd.read_csv("city_df.csv")
city_df= city_df.drop(columns = ['Unnamed: 0'])
city_df.head()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,souillac,-20.52,57.52,64.40,93,40,4.70,MU,1604285901
1,taltal,-25.40,-70.48,57.52,71,6,5.73,CL,1604285901
2,sao jose da coroa grande,20.51,76.21,72.84,51,0,4.38,IN,1604285902
3,bredasdorp,-34.53,20.04,64.40,82,98,13.87,ZA,1604285902
4,albany,42.60,-73.97,41.00,87,76,1.99,US,1604285902

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
#call the g_key
gmaps.configure(api_key=g_key)

In [4]:
# create a heatmap that displays the humidity for every city
locations = city_df[['Lat','Lng']]
humidity = city_df['Humidity']

fig = gmaps.figure()

heat_map = gmaps.heatmap_layer(locations, weights = humidity,
                              dissipating=False, max_intensity = 10,
                              point_radius = 1.5)
fig.add_layer(heat_map)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
# pull out several variables out of city_df and put in a new dataframe
new_city_df = city_df.loc[:, ['City', 'Max Temp', 'Cloudiness', 'Wind Speed']]

# set conditions for these variables
new_city_df['Max Temp']=new_city_df['Max Temp'].astype(int)
Max_Temp = (new_city_df['Max Temp'] < 80) & (new_city_df['Max Temp'] >70)
Wind_Speed = new_city_df['Wind Speed'] <10
Cloudiness = new_city_df['Cloudiness'] ==0

# create a upated dataframe based defined conditions and drop missing values
updated_city_df = new_city_df[Max_Temp& Wind_Speed& Cloudiness].dropna()
updated_city_df

                         City  Max Temp  Cloudiness  Wind Speed
2    sao jose da coroa grande        72           0        4.38
64              san cristobal        77           0        6.33
71               san patricio        77           0        6.33
93                 banda aceh        73           0        5.39
164                  san juan        77           0        6.33
165               san quintin        77           0        6.33
198                     nioro        76           0        6.06
199                sao filipe        73           0        4.16
234                   salalah        71           0        3.36
236                      doha        77           0        2.24
265         sao joao da barra        72           0        4.38
317               san anselmo        77           0        7.11
322       san marcos de colon        77           0        6.33
390                    manama        75           0        2.24
436                   chikhli        73           0        5.50
468                  san luis        77           0        6.33
477                   jamkhed        75           0        5.35
523                san rafael        77           0        6.33
538                    ormara        77           0        5.30

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
#https://maps.googleapis.com/maps/api/place/nearbysearch/json?
#location=-33.8670522,151.1957362&radius=500&types=food&name=harbour&key=YOUR_API_KEY

# add a 'Hotel Name' column
hotel_df = city_df.loc[:, ['City','Country', 'Lat','Lng']]
hotel_df['Hotel Name'] = ""
hotel_df.head()

                       City Country    Lat    Lng Hotel Name
0                  souillac      MU -20.52  57.52
1                    taltal      CL -25.40 -70.48
2  sao jose da coroa grande      IN  20.51  76.21
3                bredasdorp      ZA -34.53  20.04
4                    albany      US  42.60 -73.97

In [7]:
# call APIS and search all hotel information based on provided information
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

city_location = f"{hotel_df['Lat'][0]},{hotel_df['Lng'][0]}"
city_radius = 5000
search_types = 'hotel'
target_search = 'hotel'

params = {
    'location':city_location,
    'radius': city_radius,
    'type': search_types,
    'keyword': target_search,
    'key': g_key
}

response = requests.get(base_url, params=params)
pprint(response.json())

{'html_attributions': [],
 'results': [{'business_status': 'OPERATIONAL',
              'geometry': {'location': {'lat': -20.5122835,
                                        'lng': 57.47125659999999},
                           'viewport': {'northeast': {'lat': -20.51045702010727,
                                                      'lng': 57.47295992989272},
                                        'southwest': {'lat': -20.51315667989272,
                                                      'lng': 57.47026027010728}}},
              'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
              'name': 'Shanti Maurice Resort & Spa',
              'opening_hours': {'open_now': True},
              'photos': [{'height': 1067,
                          'html_attributions': ['<a '
                                                'href="https://maps.google.com/maps/contrib/107188048793840875874">A '
                                                'Google User</a>'],
                          'photo_reference': 'CmRaAAAAEmR7Uz22NS8OGMoJG3sYOSje1vJTunN-mEDl_lGraA6BzpsBJwWD2h-qtPl1h898FQmtIzvXRquX8WJalXZLzJ8ulKZiCkWQfBGxgFiD6db9s67s4ha80MkgH5i3WPP1EhAYuowDmlGJecmfZlagwbdQGhRM9pfOpi0he30xCRxzyqB67De5bQ',
                          'width': 1600}],
              'place_id': 'ChIJJyCvS4BlfCERPdN8e518mW8',
              'plus_code': {'compound_code': 'FFQC+3G Chemin Grenier, '
                                             'Mauritius',
                            'global_code': '5HFVFFQC+3G'},
              'rating': 4.5,
              'reference': 'ChIJJyCvS4BlfCERPdN8e518mW8',
              'scope': 'GOOGLE',
              'types': ['spa', 'lodging', 'point_of_interest', 'establishment'],
              'user_ratings_total': 654,
              'vicinity': 'Coastal Road, Saint Felix'},
             {'business_status': 'OPERATIONAL',
              'geometry': {'location': {'lat': -20.5174939,
                                        'lng': 57.55243779999999},
                           'viewport': {'northeast': {'lat': -20.51584787010728,
                                                      'lng': 57.5533794},
                                        'southwest': {'lat': -20.51854752989272,
                                                      'lng': 57.54961300000001}}},
              'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
              'name': 'Andrea Lodges',
              'opening_hours': {'open_now': True},
              'photos': [{'height': 3024,
                          'html_attributions': ['<a '
                                                'href="https://maps.google.com/maps/contrib/104290319892919853813">Péter '
                                                'Für</a>'],
                          'photo_reference': 'CmRaAAAAc7TwGPKzIm1ISFKX5RC7iK10Da6TtFp11qYYXO1lWsGsGRgSrD9R5w4QkuJv1BuXj05QgKZkmthR94pAfk0pFNjW4oz_kAaFSGLALKcgsHrG_KnSWoTra_HJyECg3y4-EhBPjbCxCtJWriKfkUYfC46FGhS-6hFWSv0v4fJFcG_9u1HkSa1Sfg',
                          'width': 4032}],
              'place_id': 'ChIJHdO5j4JkfCERNhnvcEiiQhA',
              'plus_code': {'compound_code': 'FHM2+2X Souillac, Mauritius',
                            'global_code': '5HFVFHM2+2X'},
              'rating': 4.3,
              'reference': 'ChIJHdO5j4JkfCERNhnvcEiiQhA',
              'scope': 'GOOGLE',
              'types': ['lodging', 'point_of_interest', 'establishment'],
              'user_ratings_total': 326,
              'vicinity': 'Mauritius'}],
 'status': 'OK'}

In [ ]:
# create a hotel_list to hold all hotels from search
hotel_list =[]

# define the params
params = {
    'radius': city_radius,
    'type': search_types,
    'keyword': target_search,
    'key': g_key
}

# loop through all cities and find nearby hotels and print all of their names
for index, column in hotel_df.iterrows():
    lat = column['Lat']
    lng = column['Lng']
    params['location'] = f'{lat}, {lng}'
    
    response = requests.get(base_url, params=params).json()
    #print(json.dumps(target_hotel, indent=4, sort_keys=True))
    try:
        hotel_list.append(response['results'][0]['name'])
    except:
        hotel_list.append(np.nan)
print(hotel_list)

In [ ]:
# put all hotel names into the column 'Hotel Name'
hotel_df['Hotel Name']= hotel_list
hotel_df.dropna()
hotel_df.to_csv('hotel_export.csv')

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations)
fig.add_layer(markers)
fig

# Display figure